version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Bigdev@99
      MYSQL_DATABASE: caseManagement
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

  participant-service:
    container_name: dev-participant-container
    build:
      context: ./participant_service
      dockerfile: Dockerfile.dev
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    # env_file:
    #   - participant_service/.env
    volumes:
      - ./participant_service:/app
    restart: always

volumes:
  mysql_data_dev:
